### PR TITLE
Feat/add items to cart

### PR DESCRIPTION
**Pull request by hishamss**
Added cart functionality

### CODE REVIEW

**Review by nickBarak — CHANGES_REQUESTED** [review]
In your chargeCustomerCard AJAX function you are catching errors and returning null. However, in Payment.tsx, after calling chargeCustomerCard, you are attempting to handle errors through a .catch method. I do believe this will never work as the chargeCustomerCard function can never fail as it stands now. What you can do is simply add ```throw e``` in the catch block instead of ```return null```.

In your message p element you have hard-coded the color attribute to a color that exists in styles.ts. You should add ```import { colors } from '../../styles.ts'``` and set the color to "colors.LIGHTEST" if you want this value to change along with the rest of the site.

The next things I have to say are not necessarily things you need to change, I just thought I'd include them here. You can set a default value inside the parenthesis of the useState hook. You can set styles of individual style attributes on an element through "{element reference}.style.{attribute} = {new style}". Using setAttribute("style", {new style}) will override all existing style changes, which may or may not be the desired outcome. I would _prefer_ you avoid using id's as this can create unknown conflicts with other components. I'm sure it doesn't matter for this application, but it's best practice in a component-based architecture. You could use the useRef hook as it is scoped to the component. Also you're importing from react twice.

**Comment by hishamss** [comment]
Nick, can you pull my branch locally and fix whatever you see appropriate? cause I'm not sure how to do that.

**Comment by nickBarak** [comment]
Yeah. Also to add to what I mentioned above (which I can also change), you are handling the loading of the cart from local storage in the wrong place (NavLogin). This should be handled either in the Login component after logging in or in App.tsx in a useEffect(()=>{}, [user]). Also, you are being too general with the local storage of the cart. Each user should have a particular cart associated with them (There may only be one user of a browser in many cases but not all). Also, I may need to talk to you about how you're handling the List component but I will need to look at that more first.

**Comment by mdkashem** [comment]
SyntaxError: JSON.parse: expected property name or '}' at line 1 column 3 of the JSON data
App/<
C:/Users/kasem/Desktop/ReveturePro/GitHb/Revature_Nov_6/goshopping-ui/src/App.tsx:41

  38 | 
  39 |  // Re-establish cart on user change/page refresh
  40 |  useEffect(() => {
> 41 |    let carts = JSON.parse( (localStorage.getItem('carts') || '{ guest: [] }') );
     | ^  42 |    const userCart : OrderItem[] = (user && carts[user.id]) ? carts[user.id] : carts['guest'];
  43 |    dispatch( updateCart(userCart) );
  44 |  }, [user, dispatch]);

**Comment by nickBarak** [comment]
This has been merged into dev indirectly through another branch (test-for-store/AddItemToCart, feat/searchBar)

**Pull request closed without merging**
